version: '3'

services:
  database:
    image: postgres
    restart: always
    container_name: database
    build:
      context: ./
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 5432:5432