export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'

export const SIGNIN_REQUEST = 'SIGNUP_REQUEST'
export const SIGNIN_FAILURE = 'SIGNUP_FAILURE'
export const SIGNIN_SUCCESS = 'SIGNUP_SUCCESS'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
