version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
  test_app:
    steps:
      - checkout
      - run: cd app && yarn install
      - run: cd app && yarn test
