version: 2
jobs:
  test_app:
    docker:
      - image: circleci/node:8.10
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: cd app && yarn install
      - save_cache:
          paths:
            - app/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: cd app && yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test_app
