version: 2
jobs:
  test_and_deploy:
    docker:
      - image: node:latest
    working_directory: ~/app
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
      - run:
          name: Decrypt files if branch is master
          command: |
            if [ ${CIRCLE_BRANCH} == "master" ]; then
              sh ./.circleci/decrypt-files.sh
            fi
      - run:
          name: Deploy app to S3 and api to EC2 if tests pass and branch is master
          command: |
            if [ ${CIRCLE_BRANCH} == "master" ]; then
              sh ./.circleci/deploy-app.sh
              sh ./.circleci/deploy-api.sh
            fi
workflows:
  version: 2
  tests:
    jobs:
      - test_and_deploy
