version: 2
workflows:
  version: 2
  build_and_test:
    jobs:
      - test_app
jobs:
  test_app:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: cd app && yarn install
      - run: cd app && yarn test
