module.exports = {
  MAX_NUMBER_OF_PICTURES: 4,
  BIO_MAX_SIZE: 150,
  FIRST_NAME_MAX_SIZE: 16,
  LAST_NAME_MAX_SIZE: 16,
  MAIL_MAX_SIZE: 30,
  PASSWORD_MAX_SIZE: 30,
  PASSWORD_MIN_SIZE: 8,
  USERNAME_MAX_SIZE: 16
}
