module.exports = {
  EMAIL_EXISTS: 'EMAIL_ALREADY_EXISTS',
  EMAIL_NOT_FOUND: 'EMAIL_NOT_FOUND',
  EMAIL_MISSING: 'EMAIL_MISSING',
  FIRST_NAME_MISSING: 'FIRST_NAME_MISSING',
  LAST_NAME_MISSING: 'LAST_NAME_MISSING',
  PASSWORD_MISSING: 'PASSWORD_MISSING',
  PASSWORD_TO_SHORT: 'PASSWORD_TO_SHORT',
  PHOTO_MISSING: 'PHOTO_MISSING',
  USERNAME_MISSING: 'USERNAME_MISSING',
  SIGNIN: 'INVALID_EMAIL_OR_PASSWORD',
  TOKEN_INVALID: 'TOKEN_INVALID'
}
