module.exports = {
  FIRST_NAME_WRONG_FORMAT: 'FIRST_NAME_WRONG_FORMAT',
  LAST_NAME_WRONG_FORMAT: 'LAST_NAME_WRONG_FORMAT',
  BIRTH_DATE_WRONG_FORMAT: 'BIRTH_DATE_WRONG_FORMAT',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  EMAIL_MISSING: 'EMAIL_MISSING',
  EMAIL_WRONG_FORMAT: 'EMAIL_WRONG_FORMAT',
  INVALID_EMAIL_OR_PASSWORD: 'INVALID_EMAIL_OR_PASSWORD',
  PASSWORD_MISSING: 'PASSWORD_MISSING',
  PASSWOR_WRONG_FORMAT: 'PASSWOR_WRONG_FORMAT',
  USERNAME_WRONG_FORMAT: 'USERNAME_WRONG_FORMAT'
}