export const SAVE_PROFILE_PICTURE_REQUEST = 'SAVE_PROFILE_PICTURE_REQUEST'
export const SAVE_PROFILE_PICTURE_FAILURE = 'SAVE_PROFILE_PICTURE_FAILURE'
export const SAVE_PROFILE_PICTURE_SUCCESS = 'SAVE_PROFILE_PICTURE_SUCCESS'
