export const PROFILE_PICTURE_REQUEST = 'PROFILE_PICTURE_REQUEST'
export const PROFILE_PICTURE_FAILURE = 'PROFILE_PICTURE_FAILURE'
export const PROFILE_PICTURE_SUCCESS = 'PROFILE_PICTURE_SUCCESS'

export const PICTURES_REQUEST = 'PICTURES_REQUEST'
export const PICTURES_FAILURE = 'PICTURES_FAILURE'
export const PICTURES_SUCCESS = 'PICTURES_SUCCESS'

export const GET_USER_INFOS_REQUEST = 'GET_USER_INFOS_REQUEST'
export const GET_USER_INFOS_FAILURE = 'GET_USER_INFOS_FAILURE'
export const GET_USER_INFOS_SUCCESS = 'GET_USER_INFOS_SUCCESS'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

export const PICTURE_REMOVE_REQUEST = 'PICTURE_REMOVE_REQUEST'
export const PICTURE_REMOVE_FAILURE = 'PICTURE_REMOVE_FAILURE'
export const PICTURE_REMOVE_SUCCESS = 'PICTURE_REMOVE_SUCCESS'

export const POST_LOCATION_REQUEST = 'POST_LOCATION_REQUEST'
export const POST_LOCATION_FAILURE = 'POST_LOCATION_FAILURE'
export const POST_LOCATION_SUCCESS = 'POST_LOCATION_SUCCESS'
